CREATE TABLE CLIENTE (
    CLI_IDCLIENTE INT NOT NULL AUTO_INCREMENT,
    CLI_IDUSUARIO INT NOT NULL,
    CLI_NOME VARCHAR(100) NOT NULL,
    CLI_CPF CHAR(11) UNIQUE NULL,
    CLI_EMAIL VARCHAR(100) NULL,
    CLI_TELEFONE CHAR(11) NULL,
    CLI_IMAGEM BLOB NULL,
    CLI_CEP CHAR(8) NULL,
    CLI_LOGRADOURO VARCHAR(60) NULL,
    CLI_NUMERO VARCHAR(10) NULL,
    CLI_COMPLEMENTO VARCHAR(50) NULL,
    CLI_BAIRRO VARCHAR(50) NULL,
    CLI_CIDADE VARCHAR(50) NULL,
    CLI_ESTADO VARCHAR(50) NULL,
    PRIMARY KEY (CLI_IDCLIENTE),
    FOREIGN KEY (CLI_IDUSUARIO) REFERENCES USUARIO(USU_IDUSUARIO)
);