CREATE TABLE FAVORITO (
    FAV_IDFAVORITO INT NOT NULL AUTO_INCREMENT,
    CLI_IDCLIENTE INT NOT NULL,
    PRO_IDPRODUTO INT NOT NULL,
    PRIMARY KEY (FAV_IDFAVORITO),
    FOREIGN KEY (CLI_IDCLIENTE) REFERENCES CLIENTE(CLI_IDCLIENTE),
    FOREIGN KEY (PRO_IDPRODUTO) REFERENCES PRODUTO(PRO_IDPRODUTO)
);