CREATE TABLE FORNECEDOR (
    FOR_IDFORNECEDOR INT NOT NULL AUTO_INCREMENT,
    FOR_IDUSUARIO INT NOT NULL,
    FOR_NOME VARCHAR(100) NOT NULL,
    FOR_CNPJ CHAR(14) UNIQUE NULL,
    FOR_EMAIL VARCHAR(100) NULL,
    FOR_TELEFONE CHAR(11) NULL,
    FOR_CELULAR CHAR(11) NULL,
    FOR_ENDERECO VARCHAR(100) NULL,
    FOR_LOGRADOURO VARCHAR(60) NULL,
    FOR_CEP CHAR(8) NULL,
    FOR_COMPLEMENTO VARCHAR(50) NULL,
    FOR_BAIRRO VARCHAR(50) NULL,
    FOR_NUMERO VARCHAR(10) NULL,
    FOR_CIDADE VARCHAR(50) NULL,
    FOR_ESTADO VARCHAR(50) NULL,
    PRIMARY KEY (FOR_IDFORNECEDOR),
    FOREIGN KEY (FOR_IDUSUARIO) REFERENCES USUARIO(USU_IDUSUARIO)
);