CREATE TABLE ITEM_PEDIDO (
    ITM_IDITEMPEDIDO INT NOT NULL AUTO_INCREMENT,
    PED_IDPEDIDO INT NOT NULL,
    PRO_IDPRODUTO INT NOT NULL,
    ITM_QUANTIDADE INT NOT NULL,
    PRIMARY KEY (ITM_IDITEMPEDIDO),
    FOREIGN KEY (PED_IDPEDIDO) REFERENCES PEDIDO(PED_IDPEDIDO),
    FOREIGN KEY (PRO_IDPRODUTO) REFERENCES PRODUTO(PRO_IDPRODUTO)
);