CREATE TABLE PEDIDO (
    PED_IDPEDIDO INT NOT NULL AUTO_INCREMENT,
    CLI_IDCLIENTE INT NOT NULL,
    FOR_IDFORNECEDOR INT NOT NULL,
    PED_DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PED_STATUS ENUM('PENDENTE', 'ENVIADO', 'ENTREGUE') NOT NULL,
    PRIMARY KEY (PED_IDPEDIDO),
    FOREIGN KEY (CLI_IDCLIENTE) REFERENCES CLIENTE(CLI_IDCLIENTE),
    FOREIGN KEY (FOR_IDFORNECEDOR) REFERENCES FORNECEDOR(FOR_IDFORNECEDOR)
);