CREATE TABLE PRODUTO (
    PRO_IDPRODUTO INT NOT NULL AUTO_INCREMENT,
    PRO_NOME VARCHAR(100) NOT NULL,
    PRO_DESCRICAO TEXT NOT NULL,
    PRO_PRECO DECIMAL(10, 2) NOT NULL,
    PRO_QUANTIDADE INT NOT NULL,
    PRO_IMAGEM VARCHAR(255) NOT NULL,
    FOR_IDFORNECEDOR INT NOT NULL,
    CAT_CATEGORIA ENUM('CAMISA', 'CALCADO', 'ACESSORIO','SHORTS') NOT NULL,
    PRO_TAMANHO ENUM('PP', 'P', 'M', 'G', 'GG') NOT NULL,
    PRO_COR ENUM('VERMELHO', 'AZUL', 'VERDE', 'AMARELO', 'PRETO', 'BRANCO') NOT NULL,
    PRO_SEXO ENUM('MASCULINO', 'FEMININO', 'UNISSEX') NOT NULL,
    PRO_DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PRO_IDPRODUTO),
    FOREIGN KEY (FOR_IDFORNECEDOR) REFERENCES FORNECEDOR(FOR_IDFORNECEDOR)
);