CREATE TABLE usuario (
    USU_IDUSUARIO INT NOT NULL AUTO_INCREMENT,
    TIPO_USUARIO ENUM('FORNECEDOR', 'ADMINISTRADOR') NOT NULL,
    USU_NOME VARCHAR(100) NOT NULL,
    USU_EMAIL VARCHAR(90) UNIQUE NOT NULL,
    USU_SENHA VARCHAR(100) NULL,
    USU_CPF CHAR(11) UNIQUE NULL,
    USU_TELEFONE CHAR(11) NULL,
    USU_LOGRADOURO VARCHAR(60) NULL,
    USU_NUMERO VARCHAR(10) NULL,
    USU_CIDADE VARCHAR(50) NULL,
    USU_ESTADO VARCHAR(50) NULL,
    PRIMARY KEY (USU_IDUSUARIO)
);