CREATE TABLE venda(
    VEN_IDVENDA INT NOT NULL AUTO_INCREMENT,
    CLI_IDCLIENTE INT NOT NULL,
    PRO_IDPRODUTO INT NOT NULL,
    VEN_DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VEN_QUANTIDADE INT NOT NULL,
    VEN_VALOR_TOTAL DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (VEN_IDVENDA),
    FOREIGN KEY (CLI_IDCLIENTE) REFERENCES CLIENTE(CLI_IDCLIENTE),
    FOREIGN KEY (PRO_IDPRODUTO) REFERENCES PRODUTO(PRO_IDPRODUTO)
)